const catalog=[
{id:'train',title:'The Great Train Robbery',year:1903,genre:'Western / Short',category:'Westerns',duration:12,rights:'Public domain',mediaUrl:'https://commons.wikimedia.org/wiki/Special:Redirect/file/The_Great_Train_Robbery_1903.webm'},
{id:'within',title:'Within Our Gates',year:1920,genre:'Drama',category:'Drama',duration:77,rights:'Public domain in U.S.',mediaUrl:'https://commons.wikimedia.org/wiki/Special:Redirect/file/Within_Our_Gates_(1920).webm'},
{id:'earthquake',title:'San Francisco Earthquake and Fire',year:1906,genre:'Documentary / Short',category:'History',duration:13,rights:'Public domain',mediaUrl:'https://tile.loc.gov/storage-services/media/ammem/EarlyFilmsofSanFrancisco/03734.mp4'},
{id:'night',title:'Night of the Living Dead',year:1968,genre:'Zombie Horror',category:'Horror',duration:96,rights:'Public domain in U.S. — no copyright notice',mediaUrl:'https://commons.wikimedia.org/wiki/Special:Redirect/file/Night_of_the_Living_Dead_(1968_film).webm'},
{id:'plan9',title:'Plan 9 from Outer Space',year:1959,genre:'Sci-Fi / Horror',category:'Sci-Fi',duration:79,rights:'Public domain — no copyright notice',mediaUrl:'https://commons.wikimedia.org/wiki/Special:Redirect/file/Plan_9_from_Outer_Space_(1959).webm'},
{id:'popeyeSindbad',title:'Popeye the Sailor Meets Sindbad the Sailor',year:1936,genre:'Animation / Comedy',category:'Cartoons',duration:16,rights:'Public domain — copyright not renewed',mediaUrl:'https://commons.wikimedia.org/wiki/Special:Redirect/file/Popeye_the_Sailor_Meets_Sindbad_the_Sailor.webm'},
{id:'popeyeSkate',title:'Popeye: A Date to Skate',year:1938,genre:'Animation / Comedy',category:'Cartoons',duration:8,rights:'Public domain — copyright not renewed',mediaUrl:'https://commons.wikimedia.org/wiki/Special:Redirect/file/Popeye_The_Sailor_-_67_A_Date_to_Skate.webm'},
{id:'cameraman',title:'The Cameraman',year:1928,genre:'Silent Comedy',category:'Comedy',duration:70,rights:'Public domain in U.S.',mediaUrl:'https://commons.wikimedia.org/wiki/Special:Redirect/file/The_Cameraman_(1928).webm'},
{id:'oldArizona',title:'In Old Arizona',year:1928,genre:'Western',category:'Westerns',duration:96,rights:'Public domain in U.S.',mediaUrl:'https://commons.wikimedia.org/wiki/Special:Redirect/file/In-Old-Arizona(1928)-By-Fox.webm'},
{id:'westDivide',title:'West of the Divide',year:1934,genre:'Western',category:'Westerns',duration:54,rights:'Public domain — copyright not renewed',mediaUrl:'https://commons.wikimedia.org/wiki/Special:Redirect/file/West_of_the_Divide.webm'}];
const channels=[
{no:'01',icon:'📺',name:'Retro TV',category:'Variety',desc:'A rotating mix of verified classics',playlist:['train','cameraman','popeyeSindbad','night','within','plan9']},
{no:'02',icon:'🎞️',name:'Classic Cinema',category:'Movies',desc:'Features and landmarks from cinema history',playlist:['within','cameraman','oldArizona','night']},
{no:'03',icon:'🦇',name:'Horror Theater',category:'Horror',desc:'Public-domain monsters, zombies and midnight movies',playlist:['night','plan9']},
{no:'04',icon:'🤠',name:'Western Trail',category:'Westerns',desc:'Frontier adventures and early western cinema',playlist:['train','oldArizona','westDivide']},
{no:'05',icon:'🐭',name:'Saturday Cartoons',category:'Cartoons',desc:'Vintage public-domain animation and comedy shorts',playlist:['popeyeSindbad','popeyeSkate']},
{no:'06',icon:'👽',name:'Sci-Fi Theater',category:'Sci-Fi',desc:'Flying saucers, strange worlds and atomic-age thrills',playlist:['plan9','night']},
{no:'07',icon:'🕵️',name:'Mystery & Shadows',category:'Mystery',desc:'Drama, suspense and shadowy archive cinema',playlist:['within','night']},
{no:'08',icon:'😂',name:'Comedy Club',category:'Comedy',desc:'Slapstick, silent comedy and classic laughs',playlist:['cameraman','popeyeSindbad','popeyeSkate']},
{no:'09',icon:'📡',name:'Classic TV',category:'Television',desc:'Classic-style programming while verified TV episodes are added',playlist:['popeyeSkate','train','earthquake']},
{no:'10',icon:'📰',name:'Newsreels',category:'History',desc:'Historic footage, documentaries and newsreels',playlist:['earthquake']},
{no:'11',icon:'🎭',name:'Drama Showcase',category:'Drama',desc:'Classic dramatic features',playlist:['within']},
{no:'12',icon:'🌙',name:'After Midnight',category:'Late Night',desc:'Horror, sci-fi and cult archive cinema after dark',playlist:['night','plan9','within']}];
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];const item=id=>catalog.find(x=>x.id===id);
function channelState(c){const total=c.playlist.reduce((n,id)=>n+item(id).duration*60,0),seconds=Math.floor(Date.now()/1000)%total;let cursor=0;for(let i=0;i<c.playlist.length;i++){const m=item(c.playlist[i]),len=m.duration*60;if(seconds<cursor+len)return{m,index:i,offset:seconds-cursor,total,len};cursor+=len}return{m:item(c.playlist[0]),index:0,offset:0,total,len:item(c.playlist[0]).duration*60}}
function posterMarkup(m){return `<div class="poster"><span class="year">${m.year}</span><h3>${m.title}</h3><small>${m.genre}</small></div><div class="movie-info"><small>${m.duration} min · ${m.rights}</small><br><span class="badge">PLAYABLE · RIGHTS RECORDED</span></div>`}
function renderChannels(){$('#channelGrid').innerHTML=channels.map(c=>`<article class="channel-card" data-channel="${c.no}"><span class="channel-no">${c.icon} CHANNEL ${c.no} · ${c.category}</span><div><h3>${c.name}</h3><p>${c.desc}</p></div></article>`).join('');$$('.channel-card').forEach(e=>e.onclick=()=>loadChannel(e.dataset.channel))}
function renderLibrary(q=''){q=q.toLowerCase();$('#libraryGrid').innerHTML=catalog.filter(m=>`${m.title} ${m.genre} ${m.category} ${m.year}`.toLowerCase().includes(q)).map(m=>`<article class="movie-card" data-id="${m.id}">${posterMarkup(m)}</article>`).join('');$$('.movie-card').forEach(e=>e.onclick=()=>playItem(item(e.dataset.id),0,false))}
function renderGuide(){$('#guideGrid').innerHTML=channels.map(c=>{const s=channelState(c);let t=new Date(Date.now()-s.offset*1000),idx=s.index,cells='';for(let i=0;i<3;i++){const m=item(c.playlist[idx%c.playlist.length]);cells+=`<div class="guide-program"><span class="time">${t.toLocaleTimeString([],{hour:'numeric',minute:'2-digit'})}</span><strong>${m.title}</strong><small>${m.year} · ${m.genre}</small></div>`;t=new Date(t.getTime()+m.duration*60000);idx++}return `<div class="guide-row"><div class="guide-channel"><strong>${c.icon} ${c.no} ${c.name}</strong><span>${c.category} · ${c.desc}</span></div>${cells}</div>`}).join('')}
function setInfo(m,offset,next){$('#nowTitle').textContent=m.title;$('#nowMeta').textContent=`${m.year} · ${m.genre} · ${m.rights}`;$('#progressBar').style.width=Math.min(100,offset/(m.duration*60)*100)+'%';$('#startTime').textContent=new Date(Date.now()-offset*1000).toLocaleTimeString([],{hour:'numeric',minute:'2-digit'});$('#remaining').textContent=Math.max(0,Math.ceil((m.duration*60-offset)/60))+' min remaining';if(next)$('#upNextTitle').textContent=next.title}
function updatePhysicalControls(){const v=$('#player'),playIcon=$('#playPause .control-symbol'),muteIcon=$('#muteBtn .control-symbol');if(playIcon)playIcon.textContent=v.paused?'▶':'❚❚';if(muteIcon)muteIcon.textContent=v.muted?'🔇':'🔊'}
function playItem(m,offset=0,isLive=false){setInfo(m,offset);const v=$('#player'),p=$('#playerPlaceholder');v.src=m.mediaUrl;v.style.display='block';p.style.display='none';v.onloadedmetadata=()=>{if(offset>0&&isFinite(v.duration))v.currentTime=Math.min(offset,Math.max(0,v.duration-1));v.play().catch(()=>{});updatePhysicalControls()};v.onplay=updatePhysicalControls;v.onpause=updatePhysicalControls;v.onvolumechange=updatePhysicalControls;v.onerror=()=>{v.style.display='none';p.style.display='grid';p.querySelector('p').textContent='The archive video could not load. Try another channel.'};if(isLive)v.onended=()=>loadChannel(window.currentChannel||'01');switchView('live')}
function loadChannel(no){window.currentChannel=no;const c=channels.find(x=>x.no===no),s=channelState(c),next=item(c.playlist[(s.index+1)%c.playlist.length]);setInfo(s.m,s.offset,next);playItem(s.m,s.offset,true)}
function switchView(id){$$('.view').forEach(v=>v.classList.toggle('active',v.id===id));$$('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.view===id));window.scrollTo({top:0,behavior:'smooth'})}
$$('.nav-btn').forEach(b=>b.onclick=()=>switchView(b.dataset.view));$('#search').oninput=e=>renderLibrary(e.target.value);$('#watchBtn').onclick=()=>loadChannel('03');
$('#playPause').onclick=()=>{const v=$('#player');if(!v.src)return;v.paused?v.play().catch(()=>{}):v.pause()};
$('#back10').onclick=()=>{const v=$('#player');if(v.src)v.currentTime=Math.max(0,v.currentTime-10)};
$('#forward10').onclick=()=>{const v=$('#player');if(v.src)v.currentTime=Math.min(isFinite(v.duration)?v.duration:v.currentTime+10,v.currentTime+10)};
$('#muteBtn').onclick=()=>{const v=$('#player');v.muted=!v.muted;updatePhysicalControls()};
$('#fullscreenBtn').onclick=()=>{const el=$('.tv-screen');if(document.fullscreenElement)document.exitFullscreen?.();else if(el.requestFullscreen)el.requestFullscreen();else if($('#player').webkitEnterFullscreen)$('#player').webkitEnterFullscreen()};
renderChannels();renderLibrary();renderGuide();const initial=channelState(channels.find(c=>c.no==='03'));setInfo(initial.m,initial.offset,item(channels.find(c=>c.no==='03').playlist[(initial.index+1)%channels.find(c=>c.no==='03').playlist.length]));updatePhysicalControls();