const catalog=[
{id:'train',title:'The Great Train Robbery',year:1903,genre:'Western / Short',category:'Westerns',duration:12,rights:'Public domain',mediaUrl:'https://commons.wikimedia.org/wiki/Special:Redirect/file/The_Great_Train_Robbery_1903.webm'},
{id:'within',title:'Within Our Gates',year:1920,genre:'Drama',category:'Drama',duration:77,rights:'Public domain in U.S.',mediaUrl:'https://commons.wikimedia.org/wiki/Special:Redirect/file/Within_Our_Gates_(1920).webm'},
{id:'earthquake',title:'San Francisco Earthquake and Fire',year:1906,genre:'Documentary / Short',category:'Documentary',duration:13,rights:'Public domain',mediaUrl:'https://tile.loc.gov/storage-services/media/ammem/EarlyFilmsofSanFrancisco/03734.mp4'}];
const channels=[
{no:'01',icon:'📺',name:'Retro TV',category:'Variety',desc:'A rotating mix of verified classics',playlist:['train','within','earthquake']},
{no:'02',icon:'🎞️',name:'Classic Cinema',category:'Movies',desc:'Features and silent landmarks',playlist:['within','train','earthquake']},
{no:'03',icon:'🦇',name:'Horror Theater',category:'Horror',desc:'Public-domain monsters, thrillers and midnight movies',playlist:['within','train']},
{no:'04',icon:'🤠',name:'Western Trail',category:'Westerns',desc:'Frontier adventures and early western cinema',playlist:['train']},
{no:'05',icon:'🐭',name:'Saturday Cartoons',category:'Cartoons',desc:'Vintage public-domain animation and shorts',playlist:['earthquake','train']},
{no:'06',icon:'👽',name:'Sci-Fi Theater',category:'Sci-Fi',desc:'Atomic-age science fiction and strange worlds',playlist:['train','earthquake']},
{no:'07',icon:'🕵️',name:'Film Noir',category:'Noir & Mystery',desc:'Crime, mystery, detectives and shadowy classics',playlist:['within','train']},
{no:'08',icon:'😂',name:'Comedy Club',category:'Comedy',desc:'Slapstick, silent comedy and classic laughs',playlist:['train','earthquake']},
{no:'09',icon:'📡',name:'Classic TV',category:'Television',desc:'Verified public-domain television episodes',playlist:['within','train']},
{no:'10',icon:'📰',name:'Newsreels',category:'History',desc:'Historic footage, documentaries and newsreels',playlist:['earthquake']},
{no:'11',icon:'🎭',name:'Drama Showcase',category:'Drama',desc:'Classic dramatic features and shorts',playlist:['within']},
{no:'12',icon:'🌙',name:'After Midnight',category:'Late Night',desc:'An eclectic late-night rotation of archive cinema',playlist:['within','earthquake','train']}];
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];const item=id=>catalog.find(x=>x.id===id);
function channelState(c){const total=c.playlist.reduce((n,id)=>n+item(id).duration*60,0);const seconds=Math.floor(Date.now()/1000)%total;let cursor=0;for(let i=0;i<c.playlist.length;i++){const m=item(c.playlist[i]),len=m.duration*60;if(seconds<cursor+len)return{m,index:i,offset:seconds-cursor,total,len};cursor+=len}return{m:item(c.playlist[0]),index:0,offset:0,total,len:item(c.playlist[0]).duration*60}}
function posterMarkup(m){return `<div class="poster"><span class="year">${m.year}</span><h3>${m.title}</h3><small>${m.genre}</small></div><div class="movie-info"><small>${m.duration} min · ${m.rights}</small><br><span class="badge">PLAYABLE · RIGHTS RECORDED</span></div>`}
function renderChannels(){$('#channelGrid').innerHTML=channels.map(c=>`<article class="channel-card" data-channel="${c.no}"><span class="channel-no">${c.icon} CHANNEL ${c.no} · ${c.category}</span><div><h3>${c.name}</h3><p>${c.desc}</p></div></article>`).join('');$$('.channel-card').forEach(e=>e.onclick=()=>loadChannel(e.dataset.channel,true))}
function renderLibrary(q=''){q=q.toLowerCase();$('#libraryGrid').innerHTML=catalog.filter(m=>`${m.title} ${m.genre} ${m.category} ${m.year}`.toLowerCase().includes(q)).map(m=>`<article class="movie-card" data-id="${m.id}">${posterMarkup(m)}</article>`).join('');$$('.movie-card').forEach(e=>e.onclick=()=>playItem(item(e.dataset.id),0,false))}
function renderGuide(){$('#guideGrid').innerHTML=channels.map(c=>{const s=channelState(c);let t=new Date(Date.now()-s.offset*1000),idx=s.index,cells='';for(let i=0;i<3;i++){const m=item(c.playlist[idx%c.playlist.length]);cells+=`<div class="guide-program"><span class="time">${t.toLocaleTimeString([],{hour:'numeric',minute:'2-digit'})}</span><strong>${m.title}</strong><small>${m.year} · ${m.genre}</small></div>`;t=new Date(t.getTime()+m.duration*60000);idx++}return `<div class="guide-row"><div class="guide-channel"><strong>${c.icon} ${c.no} ${c.name}</strong><span>${c.category} · ${c.desc}</span></div>${cells}</div>`}).join('')}
function setInfo(m,offset,next){$('#nowTitle').textContent=m.title;$('#nowMeta').textContent=`${m.year} · ${m.genre} · ${m.rights}`;$('#progressBar').style.width=Math.min(100,offset/(m.duration*60)*100)+'%';$('#startTime').textContent=new Date(Date.now()-offset*1000).toLocaleTimeString([],{hour:'numeric',minute:'2-digit'});$('#remaining').textContent=Math.max(0,Math.ceil((m.duration*60-offset)/60))+' min';if(next)$('#upNextTitle').textContent=next.title}
function playItem(m,offset=0,isLive=false){setInfo(m,offset);const v=$('#player'),p=$('#playerPlaceholder');v.src=m.mediaUrl;v.style.display='block';p.style.display='none';v.onloadedmetadata=()=>{if(offset>0&&isFinite(v.duration))v.currentTime=Math.min(offset,Math.max(0,v.duration-1));v.play().catch(()=>{})};v.onerror=()=>{v.style.display='none';p.style.display='grid';p.querySelector('p').textContent='The archive video could not load. Try another channel.'};if(isLive)v.onended=()=>loadChannel(window.currentChannel||'01',true);switchView('live')}
function loadChannel(no){window.currentChannel=no;const c=channels.find(x=>x.no===no),s=channelState(c),next=item(c.playlist[(s.index+1)%c.playlist.length]);setInfo(s.m,s.offset,next);playItem(s.m,s.offset,true)}
function switchView(id){$$('.view').forEach(v=>v.classList.toggle('active',v.id===id));$$('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.view===id));window.scrollTo({top:0,behavior:'smooth'})}
$$('.nav-btn').forEach(b=>b.onclick=()=>switchView(b.dataset.view));$('#search').oninput=e=>renderLibrary(e.target.value);$('#watchBtn').onclick=()=>loadChannel('01');renderChannels();renderLibrary();renderGuide();const initial=channelState(channels[0]);setInfo(initial.m,initial.offset,item(channels[0].playlist[(initial.index+1)%channels[0].playlist.length]));